root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bastion ./cmd/bastion"
entrypoint = ["./tmp/bastion", "--data-dir", "../.bastion", "start", "api", "--addr", "localhost:3148", "--log-format", "text"]
include_dir = ["cmd", "internal"]
include_ext = ["go"]
exclude_dir = ["tmp"]

[misc]
startup_banner = ""
