root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bastion-guest-proxy ./cmd/bastion-guest-proxy && go build -o ./tmp/bastion ./cmd/bastion"
entrypoint = ["./tmp/bastion", "--data-dir", "../.bastion", "start", "daemon", "--log-format", "text", "--log-level", "debug"]
include_dir = ["cmd", "internal"]
include_ext = ["go"]
exclude_dir = ["tmp"]

[misc]
startup_banner = ""
