root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bastion ./cmd/bastion"
entrypoint = ["./tmp/bastion", "start", "cluster", "--addr", "localhost:3150", "--database-url", "postgres://bastion:bastion@localhost:3152/bastion_cluster?sslmode=disable", "--archive-bucket", "bastion-templates", "--archive-endpoint", "http://localhost:3153", "--archive-region", "us-east-1", "--archive-access-key-id", "bastion", "--archive-secret-access-key", "bastion-secret", "--archive-force-path-style", "--log-format", "text", "--log-level", "debug"]
include_dir = ["cmd", "internal"]
include_ext = ["go"]
exclude_dir = ["tmp"]

[misc]
startup_banner = ""
